// shop-frontend-angular-redux/src/app/shopping-cart/components/shopping-cart-view/shopping-cart-view.component.ts
import { Component } from '@angular/core';
import { Observable } from "rxjs/Rx";
import { Product } from "../../../products/products.types";
import { select } from "@angular-redux/store/lib/src/decorators/select";
import { productsInCart } from "../../redux/selectors";
import { ShoppingCartActionCreators } from "../../redux/action-creators.service";

@Component({
    selector: 'app-shopping-cart-view',
    templateUrl: './shopping-cart-view.component.html',
    styleUrls: ['./shopping-cart-view.component.css']
})
export class ShoppingCartViewComponent {

    @select(productsInCart)
    public products:Observable<Array<Product>>;

    constructor(private shoppingCartActionCreators:ShoppingCartActionCreators) {
    }

    public removeFromCart(product:Product) {
        this.shoppingCartActionCreators.removeItemFromShoppingCart(product);
    }
}

<h1>Shopping Cart</h1>

<ul>
    <li *ngFor="let product of products | async">
        <div>
            <p>{{product.name}}</p>
            <button (click)="removeFromCart(product)">Remove</button>
        </div>
    </li>
</ul>

// shop-frontend-react/src/shopping-cart/components/ShoppingCartView.js
// @flow

import React from 'react'
import {Product} from "../../products/products.types";
import {productsInCart} from "../selectors";
import {removeItemFromShoppingCart} from "../action-creators";
import {connect} from "react-redux";

type Props = {
    products: Array<Product>,
    removeFromCart: (product: Product) => void,
}

const ShoppingCartView = (props: Props) => (
    <div>
        <h1>Shopping Cart</h1>


        <ul>
            {props.products.map(product => (
                <li>
                    <div>
                        <p>{product.name}</p>
                        <button onClick={() => props.removeFromCart(product)}>Remove</button>
                    </div>
                </li>
            ))}

        </ul>
    </div>
)

const mapStateToProps = state => ({
    products: productsInCart(state)
})

const mapDispatchToProps = dispatch => ({
    removeFromCart: (product) => {
        dispatch(removeItemFromShoppingCart(product))
    }
})

const ShoppingCartViewContainer = connect(
    mapStateToProps,
    mapDispatchToProps
)(ShoppingCartView)

export default ShoppingCartViewContainer
