// shop-frontend-react/src/products/components/ProductListItem.js
// @flow

import React from 'react'
import {ProductWithFullCategories} from "../products.types";

import './ProductListItem.css'

type Props = {
    product: ProductWithFullCategories,
    addToCart: () => void
}


const ProductListItem = (props: Props) => (
    <div className="panel panel-default root-container">
        <div className="panel-body">
            <h1>{props.product.name}</h1>

            <div className="content-container">
                <div>
                    <img alt="Product" src={props.product.image} className="product-image"/>
                </div>
                <div>
                    <p>{props.product.description}</p>
                    <p>Price: {props.product.price}</p>
                    <p> Categories:
                        {props.product.categories.map(category => (
                            <span key={category.id}>{category.name}</span>
                        ))}
                    </p>

                    <button onClick={e => props.addToCart()}>Add to Cart</button>
                </div>
            </div>
        </div>
    </div>
)

export default ProductListItem

// shop-frontend-angular-redux/src/app/products/components/product-list-item/product-list-item.component.ts
import { Component, Input } from "@angular/core";
import { ProductWithFullCategories } from "../../model/products.types";
import {ShoppingCartActions} from "../../../shopping-cart/model/redux/actions";

@Component({
    selector: 'app-product-list-item',
    templateUrl: './product-list-item.component.html',
    styleUrls: ['./product-list-item.component.css']
})
export class ProductListItemComponent {

    @Input()
    public product:ProductWithFullCategories

    constructor(private shoppingCartActions:ShoppingCartActions) {}

    public addToCart():void {
        this.shoppingCartActions.addItemToShoppingCart(this.product);
    }

}

<div class="panel panel-default root-container">
    <div class="panel-body">
        <h1>{{product.name}}</h1>

        <div class="content-container">
            <div>
                <img src="{{product.image}}" class="product-image"/>
            </div>
            <div>
                <p>{{product.description}}</p>
                <p>Price: {{product.price}}</p>
                <p> Categories:
                    <span *ngFor="let category of product.categories">
                        {{category.name}}
                    </span>
                </p>

                <button (click)="addToCart()">Add to Cart</button>
            </div>

        </div>

    </div>
</div>
